# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
The Owner is;-
         H.M. Nikil Nikesh
From ;-
       Sri Lanka 




 ⭕Language: Java Script 

 ⭕Database: Mongo db

 ⭕Server: telegram bots.business

⭕ Build Version: v1.1.5



You can contact us on*our WEBSITE *
or  Our *Admin BEE*
And also on *our group*

♾web;-
https://mrbeefamily.jimdofree.com
♾Admin Bee;-
https://t.me/Bee_helpCenter365bot_bot
♾Group;-
https://t.me/Bee_Family
